# Generated by Django 4.2.7 on 2026-02-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='skin_tone',
            field=models.CharField(blank=True, choices=[('TYPE_1', 'Type I (Pale White)'), ('TYPE_2', 'Type II (White)'), ('TYPE_3', 'Type III (Dark White)'), ('TYPE_4', 'Type IV (Light Brown)'), ('TYPE_5', 'Type V (Brown)'), ('TYPE_6', 'Type VI (Dark Brown)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('OILY', 'Oily'), ('DRY', 'Dry'), ('COMBINATION', 'Combination'), ('NORMAL', 'Normal')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_status'], name='idx_user_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='idx_user_created'),
        ),
    ]
