# Generated by Django 4.2.7 on 2026-02-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('BANNED', 'Banned')], default='ACTIVE', max_length=20),
        ),
    ]
