# Generated by Django 4.2.7 on 2026-02-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, help_text="Doctor's specialization (e.g., Dermatologist)", max_length=100),
        ),
    ]
