# Generated by Django 5.2.11 on 2026-03-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_user_otp_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('registration_data', models.JSONField(help_text='Serialized user profile & registration parameters')),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_expiry', models.DateTimeField()),
                ('otp_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pending_registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
