# Generated by Django 5.2.11 on 2026-03-22 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_pendingregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('palette', models.CharField(choices=[('default', 'Default'), ('lavender', 'Lavender'), ('matcha', 'Matcha'), ('midnight', 'Midnight'), ('sunset', 'Sunset'), ('monochrome', 'Monochrome')], default='default', max_length=20)),
                ('ai_model', models.CharField(choices=[('gemini', 'Gemini'), ('llama', 'Llama')], default='gemini', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='authentication.user')),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
    ]
